services:
  jdenticon-server:
    container_name: jdenticon-server
    build:
      context: https://github.com/nannoda/jdenticon-server.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - 16043:16043
