name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: nannoda/jdenticon-server # Replace with your Docker image name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as version tag
        run: echo "APP_VERSION=$(date +'v%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV
      
      - name: Echo current version tag
        run: echo "Version $APP_VERSION" # This will output the date-based version tag

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (for multi-arch support)
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (multi-architecture)
        uses: docker/build-push-action@v4
        with:
          context: . # Docker build context
          push: true # Push to Docker Hub
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
          platforms: linux/amd64,linux/arm64 # Define architectures
